security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backenddb
    username: backend
    password: backend
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate-dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE
  allowed-headers: Content-Type,Authorization
  exposed-headers:
  allow-credentials: true
  max-age: 3600